-- ==============================================================
-- COCKROACHDB DATABASE SCHEMA & SEED DATA FOR TECHDRIVE APP
-- ==============================================================
--
-- How to run this in CockroachDB:
-- 1. Using the Cockroach SQL CLI:
--    cockroach sql --url "postgresql://rome:<YOUR-PASSWORD>@nordic-coyote-16113.jxf.gcp-asia-southeast1.cockroachlabs.cloud:26257/defaultdb?sslmode=verify-full" -f techdrive_schema.sql
--
-- 2. Or copy-paste these queries into your database management console (e.g., DBeaver, VS Code Database Client, Cockroach Console)
--

-- Create Database if not exists
CREATE DATABASE IF NOT EXISTS techdrive;
USE techdrive;

-- 1. Users Table (Handles authentications and custom roles)
CREATE TABLE IF NOT EXISTS users (
    user_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    username VARCHAR(50) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL, -- Never store raw text in production!
    full_name VARCHAR(100) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'User', -- 'Admin', 'User'
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 2. Vehicles Table (Tracks car fleet metadata and active status)
CREATE TABLE IF NOT EXISTS vehicles (
    vehicle_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    make VARCHAR(50) NOT NULL,
    model VARCHAR(50) NOT NULL,
    daily_rate NUMERIC(10, 2) NOT NULL,
    plate_number VARCHAR(50) NOT NULL, -- Added to match UI Plate Numbers
    status VARCHAR(20) NOT NULL DEFAULT 'Available', -- 'Available', 'Rent in progress', 'In Maintenance'
    last_maintenance DATE,
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- 3. Bookings Table (Stores active and past customer bookings)
CREATE TABLE IF NOT EXISTS bookings (
    booking_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 16657 INCREMENT BY 1),
    customer_name VARCHAR(100) NOT NULL,
    address VARCHAR(255) NOT NULL,
    contact_number VARCHAR(20) NOT NULL,
    license_number VARCHAR(50) NOT NULL,
    vehicle_id INT REFERENCES vehicles(vehicle_id) ON DELETE RESTRICT,
    booking_date DATE NOT NULL,
    end_date DATE NOT NULL, -- End of the rental booking period
    status VARCHAR(20) NOT NULL DEFAULT 'Draft', -- 'Draft', 'Confirmed', 'Discarded'
    subtotal NUMERIC(10, 2) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 4. Maintenance Alerts Table (Tracks vehicle-specific warning/maintenance logs)
CREATE TABLE IF NOT EXISTS alerts (
    alert_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    vehicle_id INT REFERENCES vehicles(vehicle_id) ON DELETE CASCADE,
    description VARCHAR(255) NOT NULL,
    severity VARCHAR(20) NOT NULL DEFAULT 'Medium', -- 'Low', 'Medium', 'High'
    due_date DATE,
    is_resolved BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 5. Audit Logs Table (Tracks user authentication outcomes)
CREATE TABLE IF NOT EXISTS audit_logs (
    log_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    username VARCHAR(50) NOT NULL,
    action VARCHAR(100) NOT NULL, -- 'Login Success' or 'Login Failed'
    login_time TIMESTAMPTZ DEFAULT now()
);

-- Create optimized index keys for fast lookup
CREATE INDEX IF NOT EXISTS idx_users_username ON users(username);
CREATE INDEX IF NOT EXISTS idx_vehicles_status ON vehicles(status);
CREATE INDEX IF NOT EXISTS idx_bookings_date ON bookings(booking_date);

-- ==============================================================
-- SEED DATA PRE-POPULATION
-- ==============================================================

-- Seed Users (Passwords match C# local dictionary mock accounts)
INSERT INTO users (username, password_hash, full_name, role) VALUES
('admin', 'adminpassword', 'System Administrator', 'Admin'),
('Rei', 'PayumoPassword', 'Rei Payumo', 'Admin'),
('Kim', 'VidalPassword', 'Kim Vidal', 'User'),
('MC', 'FernandezPassword', 'MC Fernandez', 'User'),
('James', 'GonzalesPassword', 'James Gonzales', 'User')
ON CONFLICT (username) DO NOTHING;

-- Seed Fleet Vehicles (11 operational cars matching app defaults)
INSERT INTO vehicles (make, model, daily_rate, status, plate_number) VALUES
('Toyota', 'Vios', 1500.00, 'Available', 'NDG-4812'),
('Ford', 'Everest', 3500.00, 'Available', 'NFC-2930'),
('Mitsubishi', 'Mirage', 1200.00, 'Available', 'AAA-8765'),
('Toyota', 'Fortuner', 3200.00, 'Available', 'NDG-9102'),
('Toyota', 'Veloz', 2200.00, 'Available', 'NFI-4821'),
('Toyota', 'Hiace', 4000.00, 'Available', 'NDG-1667'),
('Toyota', 'Rush', 2000.00, 'Available', 'NFI-3098'),
('Ford', 'Ranger', 3000.00, 'Available', 'NFC-8371'),
('Mitsubishi', 'Xpander', 2400.00, 'Available', 'AAA-4321'),
('Toyota', 'Hilux', 2800.00, 'Available', 'NDG-7741'),
('Honda', 'BR-V', 2200.00, 'Available', 'NFK-5928');
